NAME = libft.a
SRC_FILES = ft_atoi.c \
	    	ft_bzero.c \
		ft_calloc.c \
	    	ft_isalnum.c \
	    	ft_isalpha.c \
	    	ft_isascii.c \
	    	ft_isdigit.c \
	    	ft_isprint.c \
		ft_itoa.c \
	    	ft_memchr.c \
	    	ft_memcmp.c \
	    	ft_memcpy.c \
	    	ft_memmove.c \
	    	ft_memset.c \
	    	ft_putchar_fd.c \
	    	ft_putendl_fd.c \
	    	ft_putnbr_fd.c \
	    	ft_putstr_fd.c \
	    	ft_split.c \
	    	ft_strchr.c \
	    	ft_strdup.c \
		ft_striteri.c \
		ft_strjoin.c \
	    	ft_strlcat.c \
	    	ft_strlcpy.c \
	    	ft_strlen.c \
		ft_strmapi.c \
	    	ft_strncmp.c \
	    	ft_strnstr.c \
	    	ft_strrchr.c \
		ft_strtrim.c \
	    	ft_substr.c \
		ft_tolower.c \
	    	ft_toupper.c \
			ft_printf.c \
			ft_putchar.c \
			ft_choose_print.c \
			ft_putnbr_base.c \
			ft_putnbr_ptr.c \
			ft_putstr.c \
			ft_putnbr_base_ptr.c \
			ft_strlen_printf.c \
			get_next_line.c \
			get_next_line_utils.c \

SRC_BONUS = ft_lstnew.c \
			ft_lstadd_front.c \
			ft_lstsize.c \
			ft_lstlast.c \
			ft_lstadd_back.c \
			ft_lstdelone.c \
			ft_lstclear.c \
			ft_lstiter.c \
			ft_lstmap.c \

OBJECTS = $(patsubst %.c, %.o, $(SRC_FILES))
OBJECTS_BONUS = $(patsubst %.c, %.o, $(SRC_BONUS))
INCLUDE = libft.h
CC = cc
FLAGS = -Wall -Wextra -Werror -g3

all: $(NAME)

$(NAME): $(OBJECTS)
	ar rcs $@ $(OBJECTS)

%.o: %.c $(INCLUDE)
	$(CC) $(FLAGS) -I ./ -c $< -o $@

clean:
	rm -f $(OBJECTS) $(OBJECTS_BONUS)

fclean: clean
	rm -f $(NAME)

re: fclean all

bonus: $(OBJECTS_BONUS)
	ar rcs $(NAME) $(OBJECTS_BONUS) 


.PHONY: all clean fclean re bonus 
